export const menuData = [
    {
        label:'Company',
        url:'/company'
    },
    {
        label:'Industries',
        url:'/industries/education/'
    },
    {
        label:'Digital Transformation',
        url:'/digital-transformation/content-management-digital-publishing/'
    },
    {
        label:'Products',
        url:'/products-and-platforms/e-learning-platform'
    },
    {
        label:'Careers',
        url:'/careers'
    },
    {
        label:'Blog',
        url:'/blog'
    },
    {
        label:'Contact',
        url:'/contact'
    }
];