export const menuData = [
    {
        label:'Company',
        url:'/company'
    },
    {
        label:'Industries',
        url:'/industries'
    },
    {
        label:'Digital Evolution',
        url:'/digital-evolution'
    },
    {
        label:'Products',
        url:'/products-and-platforms'
    },
    {
        label:'Careers',
        url:'/careers'
    },
    {
        label:'Blog',
        url:'/blog'
    },
    {
        label:'Contact',
        url:'/contact'
    }
];